CREATE TABLE IF NOT EXISTS Company (
	company_id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	name TEXT NOT NULL,
	descript TEXT DEFAULT '',
	PRIMARY KEY(company_id)
);

CREATE INDEX IF NOT EXISTS company_by_name_index
ON Company (name);


CREATE TABLE IF NOT EXISTS Forum (
	post_id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	poster_id INTEGER NOT NULL DEFAULT -1,
	content TEXT NOT NULL DEFAULT '',
	PRIMARY KEY(post_id)
);




CREATE TABLE IF NOT EXISTS Tag (
	tag_id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	tag_name TEXT NOT NULL UNIQUE,
	PRIMARY KEY(tag_id)
);

CREATE INDEX IF NOT EXISTS tag_id_by_tag_name_index
ON Tag (tag_name);


CREATE TABLE IF NOT EXISTS Company_Tag (
	company_id INTEGER NOT NULL,
	tag_id INTEGER NOT NULL,
	PRIMARY KEY(company_id, tag_id),
	FOREIGN KEY (company_id) REFERENCES Company(company_id) ON DELETE CASCADE,
	FOREIGN KEY (tag_id) REFERENCES Tag(tag_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS company_by_tag_index
ON Company_Tag (tag_id);


CREATE TABLE IF NOT EXISTS Company_Parents (
	company_id INTEGER NOT NULL,
	parent INTEGER NOT NULL,
	PRIMARY KEY(company_id, parent),
	FOREIGN KEY (company_id) REFERENCES Company(company_id) ON DELETE CASCADE,
	FOREIGN KEY (parent) REFERENCES Company(company_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS subsidiary_index
ON Company_Parents (parent);


CREATE TABLE IF NOT EXISTS Company_Forum (
	company_id INTEGER NOT NULL,
	post_id INTEGER NOT NULL,
	PRIMARY KEY(company_id, post_id),
	FOREIGN KEY (company_id) REFERENCES Company(company_id) ON DELETE CASCADE,
	FOREIGN KEY (post_id) REFERENCES Forum(post_id) ON DELETE CASCADE
);




CREATE TABLE IF NOT EXISTS Forum_Replies (
	post_id INTEGER NOT NULL,
	reply_id INTEGER NOT NULL,
	PRIMARY KEY(post_id, reply_id),
	FOREIGN KEY (post_id) REFERENCES Forum(post_id) ON DELETE CASCADE,
	FOREIGN KEY (reply_id) REFERENCES Forum(post_id) ON DELETE CASCADE
);