CREATE TABLE IF NOT EXISTS "Company" (
	"company_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"parent" INTEGER ARRAY NOT NULL CHECK((parent = '{}') OR (parent <@ (SELECT company_id FROM Company))),
	"name" TEXT NOT NULL,
	"desc" TEXT NOT NULL,
	"tags" INTEGER ARRAY,
	"forums" INTEGER ARRAY UNIQUE,
	PRIMARY KEY("company_id")
);


CREATE INDEX "name_index"
ON "Company" ("name");
CREATE INDEX "tag_index"
ON "Company" ("tags");
CREATE INDEX "parent_index"
ON "Company" ("parent");

CREATE TABLE IF NOT EXISTS "Forum" (
	"post_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"poster_id" INTEGER NOT NULL,
	"content" TEXT NOT NULL,
	"replies" INTEGER ARRAY NOT NULL UNIQUE CHECK((replies = '{}') OR (replies <@ (SELECT post_id FROM Forum))),
	PRIMARY KEY("post_id")
);




CREATE TABLE IF NOT EXISTS "Tag" (
	"tag_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"tag_name" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("tag_id", "tag_name")
);



ALTER TABLE "Company"
ADD FOREIGN KEY("parent") REFERENCES "Company"("company_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Company"
ADD FOREIGN KEY("forums") REFERENCES "Forum"("post_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "Company"
ADD FOREIGN KEY("tags") REFERENCES "Tag"("tag_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Forum"
ADD FOREIGN KEY("replies") REFERENCES "Forum"("post_id")
ON UPDATE NO ACTION ON DELETE CASCADE;